### ISSUE TITLE
<script>

### ISSUE THREAD

**Issue by oberstlynild** [madelsberger/if_StreamlabsParameter#3]
Hi again.

I have this command:
`$if('"<" in "$msg"', 'You are not allowed to use < after the command, as you would be able to script to the website', '$savetofile("C:\wamp64\www\playlist\chatbot\quotes\quotes.txt","<a href="https://www.youtube.com/results?search_query=$msg"><p>$msg</p></a>","$username added "$msg" to the playlist","Something went wrong")')`

I don't want people to use < after the command, as the file is it saved too i loaded on a website, and if people could add html tags (which contains <) to their request, it would be displayed on the website with the styles associated with that tag. I tested with <"h1"> tag and <"p"> tag and the above command seems to be working on everything unless <script> tag with actual javascript code inside.

Let me show you two examples for you to easier understand:

### 1) <script> request without actual javascript
!command
> <script>test</script>

Response: 
> You are not allowed to use < after the command, as you would be able to script to the website

### 2) <script> request with actual javascript

!command
> <script>document.body.style.fontSize="500px";</script>

Response:
> $if('"<" in "<script>document.body.style.fontSize="500px";</script>"', 'You are not allowed to use < after the command, as you would be able to script to the website', 'Oberstlynild added "> <script>document.body.style.fontSize="500px";</script>" to the playlist')

I've tried to disable all my scripts (yours inclusive) and add a simple command with the trigger being "!test" and the response being "<script>". That will output "***" and not "<script>" in my chat, so i got an idea that these issues is connected to each other - just can't find the solution.

Best regards Lars

![wtfTheseOutputs](https://user-images.githubusercontent.com/42640813/59847265-55f97280-9362-11e9-8e3b-12be0d04b2d1.jpg)

**Comment by madelsberger** [comment]
Hello.  Sorry for the delay; I've been looking at whether there are options to help with this issue by modifying the $if script... I concluded that anything I do to avoid this issue, would cause other commands not to work as expected.  I am looking at putting together another script you could use with $if to address this issue (and some others related issues that are likely to show up with this type of usage)...  But for now, let me explain what's going on.

So, the issue is not so much that your example contains actual javascript; it's that it contains a " character.  So when the $msg is expanded, the test expression becomes

'"<" in "<script>document.body.style.fontSize="500px";</script>"'`

so the " characters around "500px" mess up the expression so that python cannot evaluate it properly.

In general the solution is to sanitize $msg - in this case by escaping the " characters.  $if cannot know which part of the expression to sanitize, which is why I can't fix this within the $if script; but I am looking at how hard it would be to write a script to escape the quotes, as this would probably be useful in many use cases.  I'll leave this issue open for now, so that I can use it to let you know what I come up with.

That does point to another thing you should consider; if you have to sanitize the input anyway, you might want to just sanitize it in such a way that it is safe to write to the file (e.g. by replacing < with &amp;lt;) instead of rejecting "unsafe" values.

And either way, you'll also have to make sure you encode the $msg to be valid in a URL when you put it in the query string.  Point being you may need to encode the string in different ways each time you use $msg in your expression.

**Comment by madelsberger** [comment]
I've published a new parameter script at https://github.com/madelsberger/escMsg_StreamlabsParameter.git which should help with this issue.  If you still want to reject messages containing < (instead of just sanitizing them when writing to the HTML) you could use

`$if('"<" in "$escMsg"', 'You are not allowed to use < after the command, as you would be able to script to the website', '$savetofile("C:\wamp64\www\playlist\chatbot\quotes\quotes.txt","<a href="https://www.youtube.com/results?search_query=$escMsg(url)"><p>$msg</p></a>","$username added "$escMsg" to the playlist","Something went wrong")')`

But $escMsg also provides an HTML mode, so you could instead

`$savetofile("C:\wamp64\www\playlist\chatbot\quotes\quotes.txt","<a href="https://www.youtube.com/results?search_query=$escMsg(url)"><p>$escMsg(html)</p></a>","$username added "$escMsg" to the playlist","Something went wrong")`
